name: nicodeCore
version: '${project.version}'
main: de.nicode3141.nicodecore.NicodeCore
api-version: 1.19
commands:
  spawn:
    description: teleports player to spawn
    usage: /spawn
    aliases: Spawn
    permission: spawn
    permission-message: you have no permission to execute this command!
  rtp:
    description: teleports player to a random location
    usage: /rtp
    aliases: randomteleport
    permission: rtp
    permission-message: no permission!
